### ISSUE TITLE
Support const/immutable component fields

### ISSUE THREAD

**Issue by rcorre** [claudemr/entitysysd#1]
Currently, component members cannot be const/immutable:

```
@component struct Thrust {
    const float accel = 0f;
    Vector2f direction = Vector2f(0,0);
}

entity.register!Thrust();
```

The above fails with:

```
entitysysd/entitysysd/pool.d(80,9): Error: cannot modify struct *this.getPtr(n) Thrust with immutable members
entitysysd/entitysysd/entity.d(474,43): Error: template instance entitysysd.pool.Pool!(Thrust, 8192LU) error instantiating
entitysysd/entitysysd/entity.d(142,34):        instantiated from here: register!(Thrust)
src/app.d(178,42):        instantiated from here: register!(Thrust, )
```

Looking at how components are pooled, I'm not sure if there is a good way to do this without circumventing the type system, but it would be a nice feature to have.

**Comment by claudemr** [comment]
Yes, it should be corrected in a next minor release, That's in my todo's list.
And yes, somehow I must circumvent the type system to un-const field's, it's a bit trickier than I first thought.

**Comment by claudemr** [comment]
After some thought, I reckon we should not need const/immutable fields in components structures. Actually, it  would contradict the whole purpose of an entity/component design. ECS is used to deal with big set of entities with a controlled set of components.

In your example, if you need a const/immutable in your component, that means the exact same value will be repeated for all the entities, which is rather inefficient (in term of memory usage).

And if the value has to actually change at run-time than, it has to be mutable.

Why not use a struct in your "thrust management system" :

```
struct GeneralThrustProperties {
   const float accel = 0f;
   /* some more fields about general thrust behavior, like air resistance maybe */
 }
```

And in your component:

```
@component struct Thrust {
    Vector2f direction = Vector2f(0,0);
    /* specific thrust properties for each entities */
}
```

So I would have to enforce the usage of mutable fields for components, that can be done using traits, so I leave that ticket opened.

**Comment by rcorre** [comment]
My thought was that `accel` might differ between entities (e.g. a rocket and a ship both have a `Thruster` but one is faster), but does not change once set on an entitiy. So it is not constant across all components, but rather constant over the lifetime of one component.

However, I don't think this is a make-or-break issue, you can still use `private` to prevent systems from other modules from messing with certain values.

**Comment by claudemr** [comment]
Sorry for the late reply, you're right.

In a future version I'll allow to use "const" qualifier in component aggregates. Pool.opIndexAssign() will not be available in that case (it's what causes the error you mentioned). I'll also overload the register method with one that allow to initialise the component:

```
@component struct Thrust {
    const float accel = 0f;
    Vector2f direction = Vector2f(0,0);
}

Thrust t;

entity.register!Thrust(t);
```

However, I will prevent using the other qualifiers (immutable, shared or inout), for the reasons mentioned above.

**Comment by rcorre** [comment]
Sounds good, I think const will be enough in this case.

**Comment by claudemr** [comment]
Release v1.1.0 should fix the issue.

Default initialization of component is also supported now (it goes with having const fields after all).
So...

```
@component struct Thrust {
    const float accel = 5.0f;
    Vector2f direction = Vector2f(0,0);
}

entity.register!Thrust();

assert(entity.component!Thrust.accel == 5.0f);
```
