### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by Neurrone** [claudemr/entitysysd#9]
Can you add the following for easier serialization?
- a method that returns a list of all components an entity currently has.
- ability to set the ID used by an entity handle. If some components have entity pointers as members, their handles need to have their IDs changed to point to the right entities when loading.

I'm coming to D from c++, and remember having difficulty trying to add this.

**Comment by claudemr** [comment]
Good idea.

For the list of components, it's a bit tricky. I am pretty new to code introspection and compile-time programming. I may not end-up with an elegant API solution for that.

**Comment by Neurrone** [comment]
Yeah, the original Entityx author did briefly describe how to do it in c++ when I asked him about it, but I couldn't grasp the c++ metaprogramming involved as well. Hopefully someone on the D forums could help out.

**Comment by claudemr** [comment]
The problem is that the componentId used when I register a component to an entity is a run-time parameter (which actually does not change at run-time). I have to find a way to generate it at compile-time (maybe using the @component UDA).

**Comment by claudemr** [comment]
I actually used a system of registering delegates to access components of entities.
It probably could be a bit more elegant, but it works fine.
